import React from 'react';
import Head from 'next/head';
import { WithRouterProps } from 'next/dist/client/with-router';

interface P extends WithRouterProps {}

interface S {}

export class Page<PP = {}, SS = {}> extends React.Component<PP & P, SS & S> {
  renderHead() {
    return (
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    );
  }

  render(children: any) {
    return (
      <div className='page-wrapper'>
        {children}
      </div>
    );
  }
}

export default Page;
